<div class="notification-banner">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="notice">
                <strong class="title">Making changes</strong>
                Tell us what you think of these online Latin resources – <a href="http://www.smartsurvey.co.uk/s/KAVOI/" target="_blank" rel="noopener noreferrer">take our survey now</a>.
              </div>
            </div>
          </div>
        </div>
      </div>